export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
export const API_REQUEST_END = 'API_REQUEST_END';

export const AUTH_USER_REGISTER = 'AUTH_USER_REGISTER';
export const AUTH_COMPLETE_REGISTRATION = 'AUTH_COMPLETE_REGISTRATION';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SET_PASSWORD = 'AUTH_SET_PASSWORD';
export const AUTH_GET_USER = 'AUTH_GET_USER';

export const RECRUITER_QUESTIONS_LOAD_PENDING = 'RECRUITER_QUESTIONS_LOAD_PENDING';
export const RECRUITER_QUESTIONS_LOAD_RESOLVED = 'RECRUITER_QUESTIONS_LOAD_RESOLVED';
export const RECRUITER_QUESTIONS_LOAD_FAILED = 'RECRUITER_QUESTIONS_LOAD_FAILED';

export const RECRUITER_ANSWERS_SUBMIT_PENDING = 'RECRUITER_ANSWERS_SUBMIT_PENDING';
export const RECRUITER_ANSWERS_SUBMIT_RESOLVED = 'RECRUITER_ANSWERS_SUBMIT_RESOLVED';
export const RECRUITER_ANSWERS_SUBMIT_FAILED = 'RECRUITER_ANSWERS_SUBMIT_FAILED';

export const ADMIN_GET_USERS = 'ADMIN_GET_USERS';

export const ADMIN_CREATE_COMPANY = 'ADMIN_CREATE_COMPANY';
export const ADMIN_GET_COMPANIES = 'ADMIN_GET_COMPANIES';
export const ADMIN_GET_COMPANY = 'ADMIN_GET_COMPANY';
export const ADMIN_SET_COMPANY_CREATED = 'ADMIN_SET_COMPANY_CREATED';

export const ADMIN_CONFIGS_ADD_INDUSTRY_PENDING = 'ADMIN_CONFIGS_ADD_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_ADD_INDUSTRY_FAILED = 'ADMIN_CONFIGS_ADD_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_GET_INDUSTRIES_PENDING = 'ADMIN_CONFIGS_GET_INDUSTRIES_PENDING';
export const ADMIN_CONFIGS_GET_INDUSTRIES_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRIES_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED';

export const ADMIN_CONFIGS_GET_INDUSTRY_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_CREATE_LOCATION_PENDING = 'ADMIN_CONFIGS_CREATE_LOCATION_PENDING';
export const ADMIN_CONFIGS_CREATE_LOCATION_FAILED = 'ADMIN_CONFIGS_CREATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_GET_LOCATIONS = 'ADMIN_CONFIGS_GET_LOCATIONS';

export const ADMIN_CONFIGS_REMOVE_LOCATION_FAILED = 'ADMIN_CONFIGS_REMOVE_LOCATION_FAILED';
export const ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_LOCATION_FAILED = 'ADMIN_CONFIGS_UPDATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED';

export const ADMIN_CREATE_CONTACT_PERSON = 'ADMIN_CREATE_CONTACT';
export const ADMIN_SET_CONTACT_PERSON_CREATED = 'ADMIN_SET_CONTACT_PERSON_CREATED';

export const ADMIN_GET_CONTACT_PERSONS = 'ADMIN_GET_CONTACT_PERSONS';

export const ADMIN_REMOVE_CONTACT_PERSON = 'ADMIN_REMOVE_CONTACT_PERSON';

export const ADMIN_SET_CONTACT_PERSON_REMOVED = 'ADMIN_SET_CONTACT_PERSON_REMOVED';

export const ADMIN_GET_CONTACT_PERSON = 'ADMIN_GET_CONTACT_PERSON';

export const ADMIN_UPDATE_CONTACT_PERSON = 'ADMIN_UPDATE_CONTACT_PERSON';

export const ADMIN_LINK_CONTACT_PERSON = 'ADMIN_LINK_CONTACT_PERSON';

export const ADMIN_UNLINK_CONTACT_PERSON = 'ADMIN_UNLINK_CONTACT_PERSON';

export const ADMIN_SET_CONTACT_PERSON_UNLINKED = 'ADMIN_SET_CONTACT_PERSON_UNLINKED';

export const ADMIN_SET_CONTACT_PERSON_LINKED = 'ADMIN_SET_CONTACT_PERSON_LINKED';

export const CREATE_APPLICATION = 'ADMIN_CREATE_APPLICATION ';

export const ADMIN_CREATE_BRANCH_PENDING = 'ADMIN_CREATE_BRANCH_PENDING';
export const ADMIN_CREATE_BRANCH_FAILED = 'ADMIN_CREATE_BRANCH_FAILED';
export const ADMIN_CREATE_BRANCH_RESOLVED = 'ADMIN_CREATE_BRANCH_RESOLVED';

export const ADMIN_GET_BRANCHES = 'ADMIN_GET_BRANCHES';

export const ADMIN_GET_BRANCH_PENDING = 'ADMIN_GET_BRANCH_PENDING';
export const ADMIN_GET_BRANCH_FAILED = 'ADMIN_GET_BRANCH_FAILED';
export const ADMIN_GET_BRANCH_RESOLVED = 'ADMIN_GET_BRANCH_RESOLVED';

export const ADMIN_REMOVE_BRANCH_PENDING = 'ADMIN_REMOVE_BRANCH_PENDING';
export const ADMIN_REMOVE_BRANCH_FAILED = 'ADMIN_REMOVE_BRANCH_FAILED';
export const ADMIN_REMOVE_BRANCH_RESOLVED = 'ADMIN_REMOVE_BRANCH_RESOLVED';

export const ADMIN_UPDATE_BRANCH_PENDING = 'ADMIN_UPDATE_BRANCH_PENDING';
export const ADMIN_UPDATE_BRANCH_FAILED = 'ADMIN_UPDATE_BRANCH_FAILED';
export const ADMIN_UPDATE_BRANCH_RESOLVED = 'ADMIN_UPDATE_BRANCH_RESOLVED';

export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATION = 'GET_APPLICATION';

export const GET_VACANCIES = 'GET_VACANCIES';
export const GET_VACANCY = 'GET_VACANCY';
export const CREATE_VACANCY = 'CREATE_VACANCY';
export const REMOVE_VACANCY = 'REMOVE_VACANCY';
export const SET_VACANCY_CREATED = 'SET_VACANCY_CREATED';
export const SET_VACANCY_REMOVED = 'SET_VACANCY_REMOVED';

export const ADMIN_SET_CONTACT_PERSON_UPDATED = 'ADMIN_SET_CONTACT_PERSON_UPDATED';

export const ADMIN_CONFIGS_CREATE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_CREATE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_GET_DYNAMIC_FIELDS = 'ADMIN_CONFIGS_GET_DYNAMIC_FIELDS';
export const ADMIN_CONFIGS_REMOVE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_REMOVE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_UPDATE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_UPDATE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_CREATED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_CREATED';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_REMOVED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_REMOVED';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_UPDATED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_UPDATED';

export const ADMIN_GET_PROJECTS = 'ADMIN_GET_PROJECTS';
