export const GET = 'GET';
export const POST = 'POST';
export const PATCH = 'PATCH';
export const DELETE = 'DELETE';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
export const API_REQUEST_END = 'API_REQUEST_END';

export const AUTH_USER_REGISTER = 'AUTH_USER_REGISTER';
export const AUTH_COMPLETE_REGISTRATION = 'AUTH_COMPLETE_REGISTRATION';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SET_PASSWORD = 'AUTH_SET_PASSWORD';
export const AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET';
export const AUTH_STATE_RESET = 'AUTH_STATE_RESET';
export const AUTH_GET_USER = 'AUTH_GET_USER';

export const ADMIN_USER_UPDATE = 'ADMIN_USER_UPDATE';
export const ADMIN_USER_CREATE = 'ADMIN_USER_CREATE';

export const RECRUITER_QUESTIONS_LOAD_PENDING = 'RECRUITER_QUESTIONS_LOAD_PENDING';
export const RECRUITER_QUESTIONS_LOAD_RESOLVED = 'RECRUITER_QUESTIONS_LOAD_RESOLVED';
export const RECRUITER_QUESTIONS_LOAD_FAILED = 'RECRUITER_QUESTIONS_LOAD_FAILED';

export const RECRUITER_ANSWERS_SUBMIT_PENDING = 'RECRUITER_ANSWERS_SUBMIT_PENDING';
export const RECRUITER_ANSWERS_SUBMIT_RESOLVED = 'RECRUITER_ANSWERS_SUBMIT_RESOLVED';
export const RECRUITER_ANSWERS_SUBMIT_FAILED = 'RECRUITER_ANSWERS_SUBMIT_FAILED';

export const USERS_GET = 'USERS_GET';
export const ADMIN_USERS_STATE_RESET = 'ADMIN_USERS_STATE_RESET';
export const ADMIN_USER_DELETE = 'ADMIN_USER_DELETE';
export const ENTITY_COPY = 'ENTITY_COPY';
export const ENTITY_COPY_RESET_STATE = 'ENTITY_COPY_RESET_STATE';

export const ADMIN_CREATE_COMPANY = 'ADMIN_CREATE_COMPANY';
export const ADMIN_UPDATE_COMPANY = 'ADMIN_UPDATE_COMPANY';
export const ADMIN_GET_COMPANIES = 'ADMIN_GET_COMPANIES';
export const ADMIN_GET_COMPANY = 'ADMIN_GET_COMPANY';
export const ADMIN_DELETE_COMPANY = 'ADMIN_DELETE_COMPANY';
export const ADMIN_RESET_COMPANY_STATE = 'ADMIN_RESET_COMPANY_STATE';

export const ADMIN_CONFIGS_ADD_INDUSTRY_PENDING = 'ADMIN_CONFIGS_ADD_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_ADD_INDUSTRY_FAILED = 'ADMIN_CONFIGS_ADD_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_GET_INDUSTRIES_PENDING = 'ADMIN_CONFIGS_GET_INDUSTRIES_PENDING';
export const ADMIN_CONFIGS_GET_INDUSTRIES_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRIES_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED';

export const ADMIN_CONFIGS_GET_INDUSTRY_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_CREATE_LOCATION_PENDING = 'ADMIN_CONFIGS_CREATE_LOCATION_PENDING';
export const ADMIN_CONFIGS_CREATE_LOCATION_FAILED = 'ADMIN_CONFIGS_CREATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_GET_LOCATIONS = 'ADMIN_CONFIGS_GET_LOCATIONS';

export const ADMIN_CONFIGS_REMOVE_LOCATION_FAILED = 'ADMIN_CONFIGS_REMOVE_LOCATION_FAILED';
export const ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_LOCATION_FAILED = 'ADMIN_CONFIGS_UPDATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED';

export const ADMIN_CREATE_CONTACT_PERSON = 'ADMIN_CREATE_CONTACT';
export const ADMIN_SET_CONTACT_PERSON_CREATED = 'ADMIN_SET_CONTACT_PERSON_CREATED';

export const ADMIN_GET_CONTACT_PERSONS = 'ADMIN_GET_CONTACT_PERSONS';

export const ADMIN_REMOVE_CONTACT_PERSON = 'ADMIN_REMOVE_CONTACT_PERSON';

export const ADMIN_SET_CONTACT_PERSON_REMOVED = 'ADMIN_SET_CONTACT_PERSON_REMOVED';

export const ADMIN_GET_CONTACT_PERSON = 'ADMIN_GET_CONTACT_PERSON';

export const ADMIN_UPDATE_CONTACT_PERSON = 'ADMIN_UPDATE_CONTACT_PERSON';

export const ADMIN_LINK_CONTACT_PERSON = 'ADMIN_LINK_CONTACT_PERSON';

export const ADMIN_UNLINK_CONTACT_PERSON = 'ADMIN_UNLINK_CONTACT_PERSON';

export const ADMIN_SET_CONTACT_PERSON_UNLINKED = 'ADMIN_SET_CONTACT_PERSON_UNLINKED';

export const ADMIN_SET_CONTACT_PERSON_LINKED = 'ADMIN_SET_CONTACT_PERSON_LINKED';

export const CREATE_APPLICATION = 'ADMIN_CREATE_APPLICATION ';
export const UPDATE_APPLICATION = 'ADMIN_UPDATE_APPLICATION ';

export const ADMIN_CREATE_BRANCH_PENDING = 'ADMIN_CREATE_BRANCH_PENDING';
export const ADMIN_CREATE_BRANCH_FAILED = 'ADMIN_CREATE_BRANCH_FAILED';
export const ADMIN_CREATE_BRANCH_RESOLVED = 'ADMIN_CREATE_BRANCH_RESOLVED';

export const ADMIN_GET_BRANCHES = 'ADMIN_GET_BRANCHES';

export const ADMIN_GET_BRANCH_PENDING = 'ADMIN_GET_BRANCH_PENDING';
export const ADMIN_GET_BRANCH_FAILED = 'ADMIN_GET_BRANCH_FAILED';
export const ADMIN_GET_BRANCH_RESOLVED = 'ADMIN_GET_BRANCH_RESOLVED';

export const ADMIN_REMOVE_BRANCH_PENDING = 'ADMIN_REMOVE_BRANCH_PENDING';
export const ADMIN_REMOVE_BRANCH_FAILED = 'ADMIN_REMOVE_BRANCH_FAILED';
export const ADMIN_REMOVE_BRANCH_RESOLVED = 'ADMIN_REMOVE_BRANCH_RESOLVED';

export const ADMIN_UPDATE_BRANCH_PENDING = 'ADMIN_UPDATE_BRANCH_PENDING';
export const ADMIN_UPDATE_BRANCH_FAILED = 'ADMIN_UPDATE_BRANCH_FAILED';
export const ADMIN_UPDATE_BRANCH_RESOLVED = 'ADMIN_UPDATE_BRANCH_RESOLVED';

export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATION = 'GET_APPLICATION';

export const GET_VACANCIES = 'GET_VACANCIES';
export const GET_VACANCY = 'GET_VACANCY';
export const CREATE_VACANCY = 'CREATE_VACANCY';
export const UPDATE_VACANCY = 'UPDATE_VACANCY';
export const REMOVE_VACANCY = 'REMOVE_VACANCY';
export const SET_VACANCY_CREATED = 'SET_VACANCY_CREATED';
export const SET_VACANCY_UPDATED = 'SET_VACANCY_UPDATED';
export const SET_VACANCY_REMOVED = 'SET_VACANCY_REMOVED';

export const ADMIN_SET_CONTACT_PERSON_UPDATED = 'ADMIN_SET_CONTACT_PERSON_UPDATED';

export const ADMIN_CONFIGS_CREATE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_CREATE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_GET_DYNAMIC_FIELDS = 'ADMIN_CONFIGS_GET_DYNAMIC_FIELDS';
export const ADMIN_CONFIGS_REMOVE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_REMOVE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_UPDATE_DYNAMIC_FIELD = 'ADMIN_CONFIGS_UPDATE_DYNAMIC_FIELD';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_CREATED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_CREATED';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_REMOVED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_REMOVED';
export const ADMIN_CONFIGS_SET_DYNAMIC_FIELD_UPDATED = 'ADMIN_CONFIGS_SET_DYNAMIC_FIELD_UPDATED';

export const ADMIN_CONFIGS_CATEGORY_CREATE = 'ADMIN_CONFIGS_CATEGORY_CREATE';
export const ADMIN_CONFIGS_CATEGORIES_GET = 'ADMIN_CONFIGS_CATEGORIES_GET';
export const ADMIN_CONFIGS_CATEGORY_DELETE = 'ADMIN_CONFIGS_CATEGORY_DELETE';
export const ADMIN_CONFIGS_CATEGORY_UPDATE = 'ADMIN_CONFIGS_CATEGORY_UPDATE';
export const ADMIN_CONFIGS_CATEGORY_RESET_STATE = 'ADMIN_CONFIGS_CATEGORY_RESET_STATE';

export const ADMIN_CONFIGS_SUBCATEGORY_CREATE = 'ADMIN_CONFIGS_SUBCATEGORY_CREATE';
export const ADMIN_CONFIGS_SUBCATEGORIES_GET = 'ADMIN_CONFIGS_SUBCATEGORIES_GET';
export const ADMIN_CONFIGS_SUBCATEGORY_DELETE = 'ADMIN_CONFIGS_SUBCATEGORY_DELETE';
export const ADMIN_CONFIGS_SUBCATEGORY_UPDATE = 'ADMIN_CONFIGS_SUBCATEGORY_UPDATE';
export const ADMIN_CONFIGS_SUBCATEGORY_RESET_STATE = 'ADMIN_CONFIGS_SUBCATEGORY_RESET_STATE';


export const ADMIN_GET_PROJECTS = 'ADMIN_GET_PROJECTS';

export const ADMIN_DASHBOARD_STATISTICS_GET = 'ADMIN_DASHBOARD_STATISTICS_GET';

export const ADMIN_CONFIGS_STATUSES_CREATE = 'ADMIN_CONFIGS_STATUSES_CREATE';
export const ADMIN_CONFIGS_STATUSES_UPDATE = 'ADMIN_CONFIGS_STATUSES_UPDATE';
export const ADMIN_CONFIGS_STATUSES_GET = 'ADMIN_CONFIGS_STATUSES_GET';
export const ADMIN_CONFIGS_STATUSES_DELETE = 'ADMIN_CONFIGS_STATUSES_DELETE';
export const ADMIN_CONFIGS_STATUSES_RESET = 'ADMIN_CONFIGS_STATUSES_RESET';

export const ADMIN_LEAD_CREATE = 'ADMIN_LEAD_CREATE';
export const ADMIN_LEAD_UPDATE = 'ADMIN_LEAD_UPDATE';
export const ADMIN_LEADS_GET = 'ADMIN_LEADS_GET';
export const ADMIN_LEAD_DELETE = 'ADMIN_LEAD_DELETE';
export const ADMIN_LEAD_STATE_RESET = 'ADMIN_LEAD_STATE_RESET';

export const ADMIN_PROJECT_RECRUITERS_SET = 'ADMIN_PROJECT_RECRUITERS_SET';

export const ADMIN_NOTES_CREATE = 'ADMIN_NOTES_CREATE';
export const ADMIN_NOTES_GET = 'ADMIN_NOTES_GET';
export const ADMIN_NOTE_DELETE = 'ADMIN_NOTE_DELETE';
export const ADMIN_NOTES_STATE_RESET = 'ADMIN_NOTES_STATE_RESET';

export const NOTIFICATIONS_GET = 'NOTIFICATIONS_GET';
export const NOTIFICATION_PATCH = 'NOTIFICATION_PATCH';

export const COMMON_CANDIDATE_CREATE = 'COMMON_CANDIDATE_CREATE';
export const COMMON_CANDIDATES_GET = 'COMMON_CANDIDATES_GET';
export const COMMON_CANDIDATE_GET = 'COMMON_CANDIDATE_GET';
export const COMMON_CANDIDATE_DELETE = 'COMMON_CANDIDATE_DELETE';
export const COMMON_CANDIDATE_UPDATE = 'COMMON_CANDIDATE_UPDATE';
export const COMMON_CANDIDATE_STATE_RESET = 'COMMON_CANDIDATE_STATE_RESET';

export const PROJECT_GET = 'PROJECT_GET';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_UPDATE = 'PROJECT_UPDATE';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_STATE_RESET = 'PROJECT_STATE_RESET';
