export const AUTH_USER_REGISTER_PENDING = 'AUTH_USER_REGISTER_PENDING';
export const AUTH_USER_REGISTER_RESOLVED = 'AUTH_USER_REGISTER_RESOLVED';
export const AUTH_USER_REGISTER_FAILED = 'AUTH_USER_REGISTER_FAILED';

export const AUTH_COMPLETE_REGISTRATION_PENDING = 'AUTH_COMPLETE_REGISTRATION_PENDING';
export const AUTH_COMPLETE_REGISTRATION_RESOLVED = 'AUTH_COMPLETE_REGISTRATION_RESOLVED';
export const AUTH_COMPLETE_REGISTRATION_FAILED = 'AUTH_COMPLETE_REGISTRATION_FAILED';

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_RESOLVED = 'AUTH_LOGIN_RESOLVED';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_GET_USER_RESOLVED = 'AUTH_GET_USER_RESOLVED';
export const AUTH_GET_USER_FAILED = 'AUTH_GET_USER_FAILED';

export const DASHBOARD_QUESTIONS_LOAD_PENDING = 'DASHBOARD_QUESTIONS_LOAD_PENDING';
export const DASHBOARD_QUESTIONS_LOAD_RESOLVED = 'DASHBOARD_QUESTIONS_LOAD_RESOLVED';
export const DASHBOARD_QUESTIONS_LOAD_FAILED = 'DASHBOARD_QUESTIONS_LOAD_FAILED';

export const DASHBOARD_ANSWERS_SUBMIT_PENDING = 'DASHBOARD_ANSWERS_SUBMIT_PENDING';
export const DASHBOARD_ANSWERS_SUBMIT_RESOLVED = 'DASHBOARD_ANSWERS_SUBMIT_RESOLVED';
export const DASHBOARD_ANSWERS_SUBMIT_FAILED = 'DASHBOARD_ANSWERS_SUBMIT_FAILED';

export const ADMIN_GET_USERS_PENDING = 'ADMIN_GET_USERS_PENDING';
export const ADMIN_GET_USERS_RESOLVED = 'ADMIN_GET_USERS_RESOLVED';
export const ADMIN_GET_USERS_FAILED = 'ADMIN_GET_USERS_FAILED';
