export const AUTH_USER_REGISTER_PENDING = 'AUTH_USER_REGISTER_PENDING';
export const AUTH_USER_REGISTER_SUCCESS = 'AUTH_USER_REGISTER_SUCCESS';
export const AUTH_USER_REGISTER_ERROR = 'AUTH_USER_REGISTER_ERROR';

export const AUTH_COMPLETE_REGISTRATION_PENDING = 'AUTH_COMPLETE_REGISTRATION_PENDING';
export const AUTH_COMPLETE_REGISTRATION_SUCCESS = 'AUTH_COMPLETE_REGISTRATION_SUCCESS';
export const AUTH_COMPLETE_REGISTRATION_ERROR = 'AUTH_COMPLETE_REGISTRATION_ERROR';

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_GET_USER_SUCCESS = 'AUTH_GET_USER_SUCCESS';
export const AUTH_GET_USER_ERROR = 'AUTH_GET_USER_ERROR';

export const DASHBOARD_QUESTIONS_LOAD_PENDING = 'DASHBOARD_QUESTIONS_LOAD_PENDING';
export const DASHBOARD_QUESTIONS_LOAD_SUCCESS = 'DASHBOARD_QUESTIONS_LOAD_SUCCESS';
export const DASHBOARD_QUESTIONS_LOAD_ERROR = 'DASHBOARD_QUESTIONS_LOAD_ERROR';

export const DASHBOARD_ANSWERS_SUBMIT_PENDING = 'DASHBOARD_ANSWERS_SUBMIT_PENDING';
export const DASHBOARD_ANSWERS_SUBMIT_SUCCESS = 'DASHBOARD_ANSWERS_SUBMIT_SUCCESS';
export const DASHBOARD_ANSWERS_SUBMIT_ERROR = 'DASHBOARD_ANSWERS_SUBMIT_ERROR';
