export const AUTH_USER_REGISTER_PENDING = 'AUTH_USER_REGISTER_PENDING';
export const AUTH_USER_REGISTER_RESOLVED = 'AUTH_USER_REGISTER_RESOLVED';
export const AUTH_USER_REGISTER_FAILED = 'AUTH_USER_REGISTER_FAILED';

export const AUTH_COMPLETE_REGISTRATION_PENDING = 'AUTH_COMPLETE_REGISTRATION_PENDING';
export const AUTH_COMPLETE_REGISTRATION_RESOLVED = 'AUTH_COMPLETE_REGISTRATION_RESOLVED';
export const AUTH_COMPLETE_REGISTRATION_FAILED = 'AUTH_COMPLETE_REGISTRATION_FAILED';

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_RESOLVED = 'AUTH_LOGIN_RESOLVED';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_SET_PASSWORD_PENDING = 'AUTH_SET_PASSWORD_PENDING';
export const AUTH_SET_PASSWORD_RESOLVED = 'AUTH_SET_PASSWORD_RESOLVED';
export const AUTH_SET_PASSWORD_FAILED = 'AUTH_SET_PASSWORD_FAILED';

export const AUTH_GET_USER_RESOLVED = 'AUTH_GET_USER_RESOLVED';
export const AUTH_GET_USER_FAILED = 'AUTH_GET_USER_FAILED';

export const RECRUITER_QUESTIONS_LOAD_PENDING = 'RECRUITER_QUESTIONS_LOAD_PENDING';
export const RECRUITER_QUESTIONS_LOAD_RESOLVED = 'RECRUITER_QUESTIONS_LOAD_RESOLVED';
export const RECRUITER_QUESTIONS_LOAD_FAILED = 'RECRUITER_QUESTIONS_LOAD_FAILED';

export const RECRUITER_ANSWERS_SUBMIT_PENDING = 'RECRUITER_ANSWERS_SUBMIT_PENDING';
export const RECRUITER_ANSWERS_SUBMIT_RESOLVED = 'RECRUITER_ANSWERS_SUBMIT_RESOLVED';
export const RECRUITER_ANSWERS_SUBMIT_FAILED = 'RECRUITER_ANSWERS_SUBMIT_FAILED';

export const ADMIN_GET_USERS_PENDING = 'ADMIN_GET_USERS_PENDING';
export const ADMIN_GET_USERS_RESOLVED = 'ADMIN_GET_USERS_RESOLVED';
export const ADMIN_GET_USERS_FAILED = 'ADMIN_GET_USERS_FAILED';

export const ADMIN_CREATE_COMPANY_PENDING = 'ADMIN_CREATE_COMPANY_PENDING';
export const ADMIN_CREATE_COMPANY_RESOLVED = 'ADMIN_CREATE_COMPANY_RESOLVED';
export const ADMIN_CREATE_COMPANY_FAILED = 'ADMIN_CREATE_COMPANY_FAILED';

export const ADMIN_GET_COMPANIES_PENDING = 'ADMIN_GET_COMPANIES_PENDING';
export const ADMIN_GET_COMPANIES_RESOLVED = 'ADMIN_GET_COMPANIES_RESOLVED';
export const ADMIN_GET_COMPANIES_FAILED = 'ADMIN_GET_COMPANIES_FAILED';

export const ADMIN_GET_COMPANY_RESOLVED = 'ADMIN_GET_COMPANY_RESOLVED';
export const ADMIN_GET_COMPANY_FAILED = 'ADMIN_GET_COMPANY_FAILED';

export const ADMIN_CONFIGS_ADD_INDUSTRY_PENDING = 'ADMIN_CONFIGS_ADD_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_ADD_INDUSTRY_FAILED = 'ADMIN_CONFIGS_ADD_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_ADD_INDUSTRY_RESOLVED';


export const ADMIN_CONFIGS_GET_INDUSTRIES_PENDING = 'ADMIN_CONFIGS_GET_INDUSTRIES_PENDING';
export const ADMIN_CONFIGS_GET_INDUSTRIES_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRIES_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRIES_RESOLVED';

export const ADMIN_CONFIGS_GET_INDUSTRY_FAILED = 'ADMIN_CONFIGS_GET_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_GET_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_UPDATE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_PENDING';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_FAILED';
export const ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED = 'ADMIN_CONFIGS_REMOVE_INDUSTRY_RESOLVED';

export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_ADD_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_PENDING';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTIONS_RESOLVED';

export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_GET_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_PENDING';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_FAILED';
export const ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_SPECIFICATION_OPTION_RESOLVED';

export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_CREATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_PENDING';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_FAILED';
export const ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED = 'ADMIN_CONFIGS_GET_CONTACT_PERSON_ROLES_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_REMOVE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_PENDING';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_FAILED';
export const ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED = 'ADMIN_CONFIGS_UPDATE_CONTACT_PERSON_ROLE_RESOLVED';

export const ADMIN_CONFIGS_CREATE_LOCATION_PENDING = 'ADMIN_CONFIGS_CREATE_LOCATION_PENDING';
export const ADMIN_CONFIGS_CREATE_LOCATION_FAILED = 'ADMIN_CONFIGS_CREATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_CREATE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_GET_LOCATIONS_PENDING = 'ADMIN_CONFIGS_GET_LOCATIONS_PENDING';
export const ADMIN_CONFIGS_GET_LOCATIONS_FAILED = 'ADMIN_CONFIGS_GET_LOCATIONS_FAILED';
export const ADMIN_CONFIGS_GET_LOCATIONS_RESOLVED = 'ADMIN_CONFIGS_GET_LOCATIONS_RESOLVED';

export const ADMIN_CONFIGS_REMOVE_LOCATION_FAILED = 'ADMIN_CONFIGS_REMOVE_LOCATION_FAILED';
export const ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_REMOVE_LOCATION_RESOLVED';

export const ADMIN_CONFIGS_UPDATE_LOCATION_FAILED = 'ADMIN_CONFIGS_UPDATE_LOCATION_FAILED';
export const ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED = 'ADMIN_CONFIGS_UPDATE_LOCATION_RESOLVED';

export const ADMIN_CREATE_CONTACT_PERSON_PENDING = 'ADMIN_CREATE_CONTACT_PERSON_PENDING';
export const ADMIN_CREATE_CONTACT_PERSON_FAILED = 'ADMIN_CREATE_CONTACT_PERSON_FAILED';
export const ADMIN_CREATE_CONTACT_PERSON_RESOLVED = 'ADMIN_CREATE_CONTACT_PERSON_RESOLVED';

export const ADMIN_GET_CONTACT_PERSONS_PENDING = 'ADMIN_GET_CONTACT_PERSONS_PENDING';
export const ADMIN_GET_CONTACT_PERSONS_FAILED = 'ADMIN_GET_CONTACT_PERSONS_FAILED';
export const ADMIN_GET_CONTACT_PERSONS_RESOLVED = 'ADMIN_GET_CONTACT_PERSONS_RESOLVED';

export const ADMIN_REMOVE_CONTACT_PERSON_PENDING = 'ADMIN_REMOVE_CONTACT_PERSON_PENDING';
export const ADMIN_REMOVE_CONTACT_PERSON_FAILED = 'ADMIN_REMOVE_CONTACT_PERSON_FAILED';
export const ADMIN_REMOVE_CONTACT_PERSON_RESOLVED = 'ADMIN_REMOVE_CONTACT_PERSON_RESOLVED';

export const ADMIN_GET_CONTACT_PERSON_PENDING = 'ADMIN_GET_CONTACT_PERSON_PENDING';
export const ADMIN_GET_CONTACT_PERSON_FAILED = 'ADMIN_GET_CONTACT_PERSON_FAILED';
export const ADMIN_GET_CONTACT_PERSON_RESOLVED = 'ADMIN_GET_CONTACT_PERSON_RESOLVED';

export const ADMIN_UPDATE_CONTACT_PERSON_PENDING = 'ADMIN_UPDATE_CONTACT_PERSON_PENDING';
export const ADMIN_UPDATE_CONTACT_PERSON_FAILED = 'ADMIN_UPDATE_CONTACT_PERSON_FAILED';
export const ADMIN_UPDATE_CONTACT_PERSON_RESOLVED = 'ADMIN_UPDATE_CONTACT_PERSON_RESOLVED';

